### PR TITLE
add feature to close an issue

### PR DESCRIPTION
**Pull request by mfrederickson**
working towards https://github.com/errbit/errbit/issues/371

### CODE REVIEW

**Comment by mfrederickson** [comment]
Hmmm. Test is completing successfully locally, but not on Travis....

**Comment by stevecrozz** [comment]
The approach looks good, but I'm thinking close_issue should maybe be an optional thing. It seems nice because the barrier is lower for new plugins and not requiring it allows old gems that haven't yet implemented this feature to still function.

**Comment by stevecrozz** [comment]
Looks awesome @mfrederickson. Can you update the README.md with an example close_issue and perhaps squash all these commits into one or two?

**Comment by mfrederickson** [comment]
@stevecrozz I'm not sure how you want me to squash the commits-- evidently there are a couple ways (I've never done it before)...

**Comment by stevecrozz** [comment]
I usually run something like:
`git fetch` then
`git rebase -i origin/master`

That starts an 'interactive' rebase and gives you the opportunity to 'pick' the commits you want to keep and 'squash' the rest. In this case you could 'pick' 'add feature to close an issue' and squash the rest and that would leave you with one commit that has all these changes.

**Comment by stevecrozz** [comment]
This makes sense to me. Thanks!

**Pull request merged**
